version: "3"
services:
  website:
    build:
    ports:
      - "8081:80"
    volumes:
      - ./website:/var/www/html

    networks:
      - default

  API:
    image: php:apache

    ports:
      - 8000:80
    environment:
      USERNAME: toto
      PASSWORD: python

  volumes:
    -/home/centos/4DVOPS/projetdvop/simple_api/student_age.json